name: Selenium Test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v1

    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 16  # You can specify the Node.js version you need

    - name: go to this folder
      run:  cd HAH
       npm install
       npm install selenium-webdriver
       npm install mochawesome 

    - name: move to this folder
      run: cd regressiontests

    - name: Run Tests
      run:  npx mocha --no-timeouts 'parkingTax.js'  # Modify this to match your test script command