name: Selenium Test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16  # You can specify the Node.js version you need

    - name: Install Dependencies
      run: npm install

    - name: Install Selenium WebDriver
      run: npm install selenium-webdriver

    - name: Install Mochawesome
      run: npm install mochawesome

    - name: Run Tests
      run:  npx mocha --no-timeouts 'airport.js'  # Modify this to match your test script command