name: CI (Continuous Integration)

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: listing directories
        run: ls  && cd regressiontests && ls          
    
      - name: Install Dependencies
        run: npm install

      - name: Install Selenium WebDriver
        run: npm install selenium-webdriver

      - name: Install Mochawesome
        run: npm install mochawesome  

      - name: Run Tests
        run:  npm test  # Modify this to match your test script command